### ISSUE TITLE
tsDiagnostic example fails

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#11]
> ### ** Examples
> 
> N=50
> m.vector=generateAbundances(N,mode=5,probabs=TRUE)
> outH=simHubbell(N=N,I=1000,m.vector=m.vector,tend=1000)
Error in randp(d, m.vector, Smeta) : 
  randp: Both vectors must have the same length!
Calls: simHubbell -> randp
Execution halted

**Comment by hallucigenia-sparsa** [comment]
Fixed.
