### ISSUE TITLE
example speed

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#12]
The current examples are too slow for possible CRAN or BioC submission. They either have to be commented out, or made faster (fewer iterations etc). 

Examples with CPU or elapsed time > 5s
                user system elapsed
doc           25.260  0.020  25.278
limitsQuality 24.032  0.000  24.032
limits        19.340  0.004  19.344
addNoise       8.192  0.008   8.201
simHubbell     7.344  0.000   7.341

**Comment by hallucigenia-sparsa** [comment]
Fixed
