### ISSUE TITLE
check for negative values in identifyNoisetypes

### ISSUE THREAD

**Issue by fbauchinger** [hallucigenia-sparsa/seqtime#15]
I accidentally ended up with negative values for freq/spec from the stats::spectrum call in identifyNoisetypes(), which then of course threw an error.
Checking not only for 0s, but also for negative values before log(out$freq)/log(out$spec) would be could,
to avoid this in the first place. Maybe also print something out, to notify the user

**Comment by hallucigenia-sparsa** [comment]
Issue addressed.
