### ISSUE TITLE
quetions about this packages

### ISSUE THREAD

**Issue by chaichai9521** [hallucigenia-sparsa/seqtime#23]
I plan to analysis data with only 2 or 3 timepoints sampling. Does this package work well?

by the way, I saw you paper. one stool sample has lots of time point collection. if I have replicate in one time point, how could I deal with that?

**Comment by hallucigenia-sparsa** [comment]
seqtime is in development, so it is not yet a polished package, but yes, it should work. Your questions about data analysis are more general and not issues with seqtime. I recommend to discuss them elsewhere.

**Comment by chaichai9521** [comment]
but I did not see the example of your code for multiple replicate online. the data file and command in this package is for individual samples at multiple timepoints. could you shared the command for replicate?
sorry for give question here, since I don't know where can I find the answers for my questions.
