### ISSUE TITLE
function naming

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#6]
* checking S3 generic/method consistency ... WARNING
boxplot:
  function(x, ...)
boxplot.noisetypes:
  function(x, noisetypes)

plot:
  function(x, ...)
plot.noisetypes:
  function(noisetypes)

See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.

This warning is due to the fact that plot and boxplot are reserved for OO methods. If we like to use them, they need to be defined as S3/S4 class methods. 

Otherwise, changing the function names for instance to boxplot_noisetypes and plot_noisetypes could help to get rid of this warning.

Note that no warnings are allowed if the pkg is submitted to CRAN.

**Comment by antagomir** [comment]
This seems a related error: 

* checking whether the namespace can be loaded with stated dependencies ... WARNING
Error: object 'boxplot' not found whilst loading namespace 'seqtime'
Execution halted

**Comment by hallucigenia-sparsa** [comment]
Function renamed. Fixed.
