### ISSUE TITLE
library/require

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#7]
R CMD check gives

* checking dependencies in R code ... WARNING
'library' or 'require' calls not declared from:
  ‘infotheo’ ‘randomForest’ ‘sde’
'library' or 'require' calls in package code:
  ‘ggplot2’ ‘infotheo’ ‘randomForest’ ‘reshape2’ ‘sde’
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.

-> It would be good practice to import the required packages (see R/firstlib.R in the next Pull Request that I'll make today) and assume that the user has those. Checking library availability within the functions is not good practice in general, although it is understandable if the package is not intended for wider distribution.

**Comment by hallucigenia-sparsa** [comment]
Fixed with firstlib.R
