### ISSUE TITLE
data

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#8]
There seems to be something to note with data commands:

Found the following calls to data() loading into the global environment:
File ‘seqtime/R/assignTaxonLevelsToA.R’:
  data("david_stool_lineages")
  data("david_stoolA_otus")
  data("david_stoolA_metadata")
  data("david_stoolB_otus")
  data("david_stoolB_metadata")
File ‘seqtime/R/generateTS.R’:
  data("david_stoolA_otus")
  data("david_stoolA_metadata")
  data("david_stoolB_otus")
  data("david_stoolB_metadata")
See section ‘Good practice’ in ‘?data’.

-> I did not investigate this further, looking at help(data) could elucidate this issue.

**Comment by antagomir** [comment]
I think the problem could be that these data sets are loaded within functions (assignTaxonLevelsToA at least). This may not be recommended in R.

**Comment by hallucigenia-sparsa** [comment]
Yes indeed, non-exposed function assignTaxonLevelsToA calls data internally. This function needs more work, for the moment the example is outcommented with \dontrun{}

**Comment by hallucigenia-sparsa** [comment]
assignTaxonLevelsToA was polished, function-internal calls to data were removed.
