### ISSUE TITLE
assignTaxonLevelsToA example fails

### ISSUE THREAD

**Issue by antagomir** [hallucigenia-sparsa/seqtime#9]
> ### ** Examples
> 
>   stoolA <- assignTaxonLevelsToA(stoolA,type="stoola")
Error in nrow(A) : object 'stoolA' not found
Calls: assignTaxonLevelsToA -> nrow
Execution halted

The stoolA argument in the function input is not defined in the example, and the automated check fails.

**Comment by hallucigenia-sparsa** [comment]
Further polishing needed for assignTaxonLevelsToA, for the moment outcommented.

**Comment by hallucigenia-sparsa** [comment]
assignTaxonLevelsToA was polished.
